linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  revive:
    enable-all-rules: true
    rules:
      - name: line-length-limit
        disabled: true
      - name: unhandled-error
        disabled: true
      - name: banned-characters
        disabled: true

linters:
  disable-all: true
  enable:
    - revive
    - gocritic
    - gosec
    - prealloc
    - govet
    - staticcheck

issues:
  exclude-use-default: false
