version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: md-paste-macos
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/md-paste
    binary: md-paste

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: md-paste
    repository:
      owner: stn1slv
      name: homebrew-tap
      # We need a custom token to push to a different repository
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/stn1slv/md-paste"
    description: "Convert rich text on the macOS clipboard to Markdown"
    license: "MIT"
    test: |
      system "#{bin}/md-paste", "--help"
